server:
  port: 8090
spring:
  application:
    name: hello-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true
  instance:
    hostname: localhost